package org.agmas.noellesroles.roles.amnesiac;

import org.agmas.noellesroles.registry.NoellesEventIds;
import org.agmas.noellesroles.registry.NoellesRoleRegistry;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.entity.PlayerBodyEntity;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.record.GameRecordManager;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.ActionResult;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;

/**
 * 失忆患者与尸体交互后继承尸体原主身份。
 */
public final class AmnesiacRoleSelectionHandler {
    private static boolean initialized = false;

    private AmnesiacRoleSelectionHandler() {
    }

    public static void init() {
        if (initialized) {
            return;
        }
        initialized = true;

        UseEntityCallback.EVENT.register((player, world, hand, entity, hitResult) -> {
            if (world.isClient() || !(player instanceof ServerPlayerEntity amnesiac)) {
                return ActionResult.PASS;
            }
            if (!amnesiac.interactionManager.getGameMode().isSurvivalLike()) {
                return ActionResult.PASS;
            }

            GameWorldComponent gameWorld = GameWorldComponent.KEY.get(world);
            if (!gameWorld.isRole(player, NoellesRoleRegistry.AMNESIAC)) {
                return ActionResult.PASS;
            }
            if (!(entity instanceof PlayerBodyEntity body)) {
                return ActionResult.PASS;
            }

            Role inheritedRole = gameWorld.getRole(body.getPlayerUuid());
            if (inheritedRole == null) {
                return ActionResult.PASS;
            }

            /*
             * 这里必须走 GameWorldComponent#addRole，而不是只改组件字段：
             * Wathe 会在这个入口记录角色变更回放，Harpy/其它扩展也会从最终角色映射读取身份。
             */
            gameWorld.addRole(player, inheritedRole);
            ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, inheritedRole);
            PlayerShopComponent.KEY.get(player).setBalance(200);

            NbtCompound extra = new NbtCompound();
            extra.putUuid("corpse_owner", body.getPlayerUuid());
            GameRecordManager.recordGlobalEvent(amnesiac.getServerWorld(), NoellesEventIds.AMNESIAC_ROLE_STOLEN_EVENT, amnesiac, extra);

            if (inheritedRole.equals(WatheRoles.VIGILANTE)) {
                amnesiac.giveItemStack(WatheItems.REVOLVER.getDefaultStack());
            }
            sendRoleAnnouncement(amnesiac, gameWorld, inheritedRole);
            return ActionResult.CONSUME;
        });
    }

    private static void sendRoleAnnouncement(ServerPlayerEntity player, GameWorldComponent gameWorld, Role role) {
        int announcementIndex;
        if (Harpymodloader.VANNILA_ROLES.contains(role)) {
            announcementIndex = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(
                    role.equals(WatheRoles.VIGILANTE)
                            ? RoleAnnouncementTexts.VIGILANTE
                            : role.equals(WatheRoles.KILLER)
                            ? RoleAnnouncementTexts.KILLER
                            : RoleAnnouncementTexts.CIVILIAN
            );
        } else {
            announcementIndex = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role));
        }

        ServerPlayNetworking.send(
                player,
                new AnnounceWelcomePayload(announcementIndex, gameWorld.getAllKillerTeamPlayers().size(), 0)
        );
    }
}
