package org.agmas.noellesroles.roles.goddess;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.Text;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.noellesroles.AbilityPlayerComponent;
import org.agmas.noellesroles.Noellesroles;
import org.agmas.noellesroles.packet.role.goddess.GoddessC2SPacket;

import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class GoddessAbility {

    private GoddessAbility() {
        // 工具类，禁止实例化
    }

    /**
     * 处理圣母的技能请求
     * @param payload 客户端发送的数据包
     * @param player  技能使用玩家（圣母）
     */
    public static void handle(GoddessC2SPacket payload, ServerPlayerEntity player) {
        var server = player.getServer();
        if (server == null) return;

        var gameWorld = GameWorldComponent.KEY.get(player.getWorld());
        if (!gameWorld.isRole(player, Noellesroles.GODDESS)) return;

        var ability = AbilityPlayerComponent.KEY.get(player);
        if (ability.cooldown > 0) return;

        var target = server.getPlayerManager().getPlayer(payload.target());
        if (target == null) return;
        // 增加存活检查（与洗脑师保持一致）
        if (target.isSpectator() || !target.isAlive()) return;
        if (target.equals(player)) return;

        // ----- 随机选择好人角色 -----
        List<Role> availableRoles = new ArrayList<>(WatheRoles.ROLES);
        availableRoles.removeIf(role ->
                !role.isInnocent() ||                // 不是好人
                        role.canUseKiller() ||                // 是杀手（或中立杀手）
                        role.equals(Noellesroles.GODDESS) ||   // 排除圣母自身
                        HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath())
        );
        if (availableRoles.isEmpty()) {
            availableRoles.add(WatheRoles.CIVILIAN);
        }
        Collections.shuffle(availableRoles);
        Role selectedRole = availableRoles.getFirst();
        // ---------------------------

        gameWorld.addRole(target, selectedRole);

        // 重置商店余额
        PlayerShopComponent shop = PlayerShopComponent.KEY.get(target);
        shop.setBalance(0);
        shop.sync();

        // 给予左轮手枪
        target.giveItemStack(WatheItems.REVOLVER.getDefaultStack());

        // 转变角色后计算当前存活杀手数量（此时目标已排除）
        long aliveKillers = server.getPlayerManager().getPlayerList().stream()
                .filter(p -> dev.doctor4t.wathe.game.GameFunctions.isPlayerAliveAndSurvival(p) && gameWorld.canUseKillerFeatures(p))
                .count();
        int killersCount = (int) aliveKillers;

        // 发送欢迎信息
        if (Harpymodloader.VANNILA_ROLES.contains(selectedRole)) {
            ServerPlayNetworking.send(target, new AnnounceWelcomePayload(
                    RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(selectedRole == WatheRoles.CIVILIAN ?
                            RoleAnnouncementTexts.CIVILIAN : RoleAnnouncementTexts.VIGILANTE),
                    killersCount,
                    0
            ));
        } else {
            ServerPlayNetworking.send(target, new AnnounceWelcomePayload(
                    RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(
                            Harpymodloader.autogeneratedAnnouncements.get(selectedRole)),
                    killersCount,
                    0
            ));
        }

        // 设置圣母冷却 (60秒)
        ability.setCooldown(60 * 20);
        ability.sync();

        // 发送拯救提示（白色）
        target.sendMessage(Text.translatable("tip.goddess.saved")
                .withColor(Color.WHITE.getRGB()), true);
    }
}