package org.agmas.noellesroles.roles.brainwasher;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.PlayerShopComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.Text;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.noellesroles.AbilityPlayerComponent;
import org.agmas.noellesroles.Noellesroles;
import org.agmas.noellesroles.packet.role.brainwasher.BrainwasherC2SPacket;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class BrainwasherAbility {

    private BrainwasherAbility() {
        // 工具类，禁止实例化
    }

    /**
     * 处理洗脑师的技能请求
     * @param payload 客户端发送的数据包
     * @param player  技能使用玩家（洗脑师）
     */
    public static void handle(BrainwasherC2SPacket payload, ServerPlayerEntity player) {
        var gameWorld = GameWorldComponent.KEY.get(player.getWorld());
        if (!gameWorld.isRole(player, Noellesroles.BRAINWASHER)) return;

        var ability = AbilityPlayerComponent.KEY.get(player);
        if (ability.cooldown > 0) return; // 冷却中

        var target = player.getServer().getPlayerManager().getPlayer(payload.target());
        if (target == null) return;
        if (target.isSpectator() || !target.isAlive()) return;
        if (target.equals(player)) return; // 不能洗脑自己

        // ----- 随机选择杀手角色（与死灵法师逻辑一致）-----
        List<Role> availableKillerRoles = new ArrayList<>(WatheRoles.ROLES);
        availableKillerRoles.removeIf(role ->
                !role.canUseKiller() || // 不是杀手（包括中立杀手？canUseKiller 通常杀手为 true）
                        role.equals(Noellesroles.BRAINWASHER) || // 排除洗脑师自身
                        Harpymodloader.VANNILA_ROLES.contains(role) || // 排除原版杀手（优先使用自定义）
                        HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath())
        );
        if (availableKillerRoles.isEmpty()) {
            // 若没有可用自定义杀手，则使用原版杀手
            availableKillerRoles.add(WatheRoles.KILLER);
        }
        Collections.shuffle(availableKillerRoles);
        Role selectedKillerRole = availableKillerRoles.getFirst();
        // ------------------------------------------------

        // 将目标转变为该杀手角色
        gameWorld.addRole(target, selectedKillerRole);

        // 设置杀手商店余额（200）
        PlayerShopComponent shop = PlayerShopComponent.KEY.get(target);
        shop.setBalance(200);
        shop.sync();

        // 发送欢迎信息（告知新角色）
        if (Harpymodloader.VANNILA_ROLES.contains(selectedKillerRole)) {
            ServerPlayNetworking.send(target, new AnnounceWelcomePayload(
                    RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(RoleAnnouncementTexts.KILLER),
                    gameWorld.getAllKillerTeamPlayers().size(),
                    0
            ));
        } else {
            ServerPlayNetworking.send(target, new AnnounceWelcomePayload(
                    RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(
                            Harpymodloader.autogeneratedAnnouncements.get(selectedKillerRole)),
                    gameWorld.getAllKillerTeamPlayers().size(),
                    0
            ));
        }

        // 设置洗脑师冷却 (60秒 = 1200 ticks)
        ability.setCooldown(60 * 20);
        ability.sync();

        // 给目标发送提示
        target.sendMessage(Text.translatable("tip.brainwasher.brainwashed")
                .withColor(0xFF69B4), true);
    }
}